Add mapping for Oracle Linux for internal TF
packit/packit-service pull request #1186
Opened 2021-08-03 14:10 UTC by lachmanfrantisek

Signed-off-by: Frantisek Lachman <flachman@redhat.com>

Fixes: packit/packit-service#1164

@thrix @bocekm

---

You can use `oraclelinux-7`/`oraclelinux-8` chroots for build and test your package for Oracle Linux.

2021-08-05 10:15 UTC, bocekm requested changes

2021-08-05 10:15 UTC, bocekm commented on packit_service/worker/testing_farm.py
> +                return "Oracle-Linux-8.3"
```suggestion
                return "Oracle-Linux-8.4"
```
We need OL 8.4 as [we don't allow converting OL 8.3 anymore](https://github.com/oamg/convert2rhel/pull/299/files#diff-1e030442df599479d1af356a7eaa61a744973513548846a1a885b8eaca6f489cR38).

2021-08-06 09:34 UTC, TomasTomecek approved these changes

2021-08-06 10:35 UTC, bocekm approved these changes

2021-08-06 10:48 UTC, merged